generate:
  lm_model: "gpt-4o-mini"
  input_length: 32
  output_length: 32
  num_of_examples: 72
  # concept_path: "<your local csv file path>"
  concept_path: "axbench/data/gemma-2-2b_20-gemmascope-res-16k.json"
  max_concepts: 10
  master_data_dir: "axbench/data"
  seed: 42

train:
  model_name: "google/gemma-2-2b"
  layer: 20
  component: "res"
  seed: 42
  use_bf16: true
  models: 
    ReAX:
      batch_size: 6
      n_epochs: 12
      topk: 1
      lr: 0.003
      coeff_l1_loss: 0.008
    L1LinearProbe:
      batch_size: 6
      n_epochs: 12
      lr: 0.003
      coeff_l1_loss: 0.1

inference:
  use_bf16: true
  models: ["ReAX", "PromptSteering", "L1LinearProbe", "GemmaScopeSAE"] 
  model_name: "google/gemma-2-2b"
  # latent related params
  input_length: 32
  latent_num_of_examples: 20
  latent_batch_size: 128
  # steering related params
  steering_model_name: "google/gemma-2-2b-it"
  steering_datasets: ["AlpacaEval"]
  steering_batch_size: 24
  steering_output_length: 128
  steering_num_of_examples: 10 # number of examples per concept
  steering_factors: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0] # number of steering factors per example
  # master data dir is shared across all jobs.
  master_data_dir: "axbench/data"
  seed: 42
  lm_model: "gpt-4o-mini"
  # generation related params
  temperature: 0.7

evaluate:
  models: ["ReAX", "PromptSteering", "L1LinearProbe", "GemmaScopeSAE"]
  latent_evaluators: [
    "AUCROCEvaluator",
    "HardNegativeEvaluator",
  ]
  steering_evaluators: [
    "PerplexityEvaluator", 
    "LMJudgeEvaluator",
  ]
  winrate_split_ratio: 0.5 # this is for steering only, we use a separate partition for factor selection.
  # Number of processes to run in parallel for steering evaluation.
  num_of_workers: 32
  lm_model: "gpt-4o-mini"
  run_winrate: true
  winrate_baseline: "PromptSteering"
  # master data dir is shared across all jobs.
  master_data_dir: "axbench/data"

